# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Statistical GIS Mapping Techniques To Forecast Future Presidential Elections
email: edgarjarguello@gmail.com
description: >- # this means to ignore newlines until "baseurl:" Write an awesome description
 This is the landing page for my Fall 2021 Semester Project for AIT 722, Geo-Social, Data Analytics 
 class at George Mason University (GMU). This project exploits exploratory and explanatory analysis of 
 specific socio-economic and Temporal variables (i.e. college degree, blue collar worker, etc.) which correlated 
 with Republican votes in the 2016 Presidential Election. Further Geographic Weighted Regression (GWR) analysis will be performed 
 with new variables (vaccination rates & CDS SVI index) to predict the Democratic vote in the upcoming 2024 US Presidential election.
baseurl: "earguel/earguel.github.io/" # the subpath of your site, e.g. /blog
url: "https://earguel.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
